### ISSUE TITLE
Readme - Add LED strip status

### ISSUE THREAD

**Issue by jellewie** [jellewie/Arduino-CocktailMachine#17]
For example:

The LED strip will:
- Blink on boot 
- Show when homing (ColorHoming)
- Show when homing failed (ColorHomeFail)
- Show a rainbow to signal we are done and IDLE 
- Show with dispenser is currently being processes/selected (ColorMoveBase + ColorMoveActive)

**Comment by jellewie** [comment]
I believe there was also a feature buildin, that the LEDs would dimm after its been in IDLE mode for some time

**Comment by Selbiecookie** [comment]
Fixed with > c44c4b4
